application: device-key-value
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /add/
  script: main.app
  login: admin
  secure: always

- url: /delete/
  script: main.app
  login: admin
  secure: always

- url: /
  script: main.app
  secure: optional
