application: device-key-value
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /add/
  script: add.app
  login: admin
- url: /.*
  script: device_key_value.app

libraries:
- name: webapp2
  version: latest
